import React, { useState, useEffect } from 'react'
import { DOMAINS, PRACTICES, getCoherenceState, getCoherenceScore as _getCS } from '../../data'
const getCoherenceScore = (s) => { if(typeof _getCS==='function') return _getCS(s); const s1=(s?.d1||0)*1.5; const s2=(s?.d2||0)+(s?.d3||0)+(s?.d4||0)+(s?.d5||0); return Math.round((s1+s2)/6.5) }

export default function PractitionerView({ checked, onboardingProfile }) {
  const [copied, setCopied] = useState(false)
  const bdr = '0.5px solid rgba(0,0,0,0.08)'
  const today = new Date()
  const todayLocal = today.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })

  // Build 7-day resonance data
  const weekData = DOMAINS.map(d => {
    let total = 0
    for (let i = 6; i >= 0; i--) {
      const dt = new Date(today); dt.setDate(today.getDate() - i)
      const dc = checked[dt.toDateString()] || {}
      const done = PRACTICES[d.id].filter((_, j) => dc[`${d.id}_${j}`]).length
      total += Math.round((done / PRACTICES[d.id].length) * 100)
    }
    return { ...d, avg: Math.round(total / 7) }
  })

  const weekScores = Object.fromEntries(weekData.map(d => [d.id, d.avg]))
  const coherenceScore = getCoherenceScore(weekScores)
  const coherenceState = getCoherenceState(coherenceScore)
  const weakest = [...weekData].sort((a,b)=>a.avg-b.avg)[0]
  const strongest = [...weekData].sort((a,b)=>b.avg-a.avg)[0]
  const userName = onboardingProfile?.userName || 'Client'
  const weekLabel = `Week of ${todayLocal}`

  const shareText = `${userName} — Quintave Coherence Report\n${weekLabel}\n\nOverall coherence: ${coherenceScore}/100 (${coherenceState.label})\n\n${weekData.map(d=>`${d.name}: ${d.avg}%`).join('\n')}\n\nHighest resonance: ${strongest.name}\nPrimary interference: ${weakest.name}\n\nGenerated by Quintave — quintave.vercel.app`

  const copyReport = () => {
    navigator.clipboard.writeText(shareText).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 3000)
    })
  }

  return (
    <div style={{ background: '#F4F3F0', minHeight: '100vh', padding: '32px 24px', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' }}>
      <div style={{ maxWidth: 560, margin: '0 auto' }}>

        {/* Header */}
        <div style={{ marginBottom: 24 }}>
          <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: '0.12em', textTransform: 'uppercase', color: '#888', marginBottom: 6 }}>Quintave · Practitioner Report</div>
          <div style={{ fontSize: 26, fontWeight: 700, letterSpacing: '-0.02em', color: '#1a1a18', marginBottom: 4 }}>{userName}</div>
          <div style={{ fontSize: 13, color: '#888' }}>{weekLabel}</div>
        </div>

        {/* Coherence state */}
        <div style={{ background: coherenceState.bg, borderRadius: 14, border: `1.5px solid ${coherenceState.color}30`, padding: '20px 22px', marginBottom: 14 }}>
          <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: coherenceState.color, marginBottom: 6 }}>Current coherence state</div>
          <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 6 }}>
            <div style={{ fontSize: 36, fontWeight: 700, color: coherenceState.color, lineHeight: 1 }}>{coherenceScore}</div>
            <div style={{ fontSize: 14, color: '#888' }}>/100</div>
            <div style={{ fontSize: 16, fontWeight: 600, color: coherenceState.color, marginLeft: 4 }}>{coherenceState.label}</div>
          </div>
          <div style={{ fontSize: 12, color: '#5F5E5A', lineHeight: 1.65 }}>{coherenceState.desc}</div>
        </div>

        {/* 7-day resonance bars */}
        <div style={{ background: '#fff', borderRadius: 14, border: bdr, padding: '18px 20px', marginBottom: 14 }}>
          <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>7-day resonance by frequency body</div>
          <div style={{ fontSize: 11, color: '#888', marginBottom: 14 }}>Average daily practice completion this week</div>
          {weekData.map((d, i) => (
            <div key={d.id} style={{ marginBottom: i < 4 ? 12 : 0 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
                <div style={{ width: 24, height: 24, borderRadius: 6, background: d.bg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, flexShrink: 0 }}>{d.icon}</div>
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 3 }}>
                    <span style={{ fontSize: 12, fontWeight: 600 }}>{d.name}</span>
                    <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                      {d.id === weakest.id && d.id !== strongest.id && <span style={{ fontSize: 10, padding: '1px 6px', borderRadius: 99, background: '#FCEBEB', color: '#A32D2D', fontWeight: 600 }}>focus here</span>}
                      {d.id === strongest.id && weekData.some(x => x.avg > 0) && <span style={{ fontSize: 10, padding: '1px 6px', borderRadius: 99, background: '#E1F5EE', color: '#085041', fontWeight: 600 }}>strongest</span>}
                      <span style={{ fontSize: 12, fontWeight: 700, color: d.avg >= 60 ? d.color : '#E24B4A' }}>{d.avg}%</span>
                    </div>
                  </div>
                  <div style={{ height: 7, borderRadius: 99, background: '#EEEDE9', overflow: 'hidden' }}>
                    <div style={{ height: 7, borderRadius: 99, background: d.color, width: `${d.avg}%`, transition: 'width 0.5s' }}/>
                  </div>
                </div>
                {d.id === 'd1' && <div style={{ fontSize: 9, padding: '1px 5px', borderRadius: 99, background: '#EEEDFE', color: '#3C3489', fontWeight: 700 }}>FORK</div>}
              </div>
            </div>
          ))}
        </div>

        {/* Key insights */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 14 }}>
          <div style={{ background: strongest.bg, borderRadius: 12, border: `1px solid ${strongest.color}20`, padding: '14px 16px' }}>
            <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: strongest.color, marginBottom: 6 }}>Highest resonance</div>
            <div style={{ fontSize: 16, fontWeight: 700, color: strongest.text }}>{strongest.icon} {strongest.name}</div>
            <div style={{ fontSize: 13, color: strongest.text, opacity: 0.8 }}>{strongest.avg}% this week</div>
          </div>
          <div style={{ background: weakest.bg, borderRadius: 12, border: `1px solid ${weakest.color}20`, padding: '14px 16px' }}>
            <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: weakest.color, marginBottom: 6 }}>Primary interference</div>
            <div style={{ fontSize: 16, fontWeight: 700, color: weakest.text }}>{weakest.icon} {weakest.name}</div>
            <div style={{ fontSize: 13, color: weakest.text, opacity: 0.8 }}>{weakest.avg}% this week</div>
          </div>
        </div>

        {/* Session prep note */}
        <div style={{ background: '#1a1a18', borderRadius: 12, padding: '16px 18px', marginBottom: 20 }}>
          <div style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: '#888780', marginBottom: 6 }}>For our session</div>
          <div style={{ fontSize: 13, color: '#C0BEBA', lineHeight: 1.7 }}>
            {weekData.every(d => d.avg === 0)
              ? 'No practices logged this week yet. Complete practices to generate meaningful resonance data for your session.'
              : <>{`Primary focus: `}<strong style={{ color: '#fff' }}>{weakest.name}</strong>{` — ${weakest.avg}% resonance this week.${weakest.avg < 40 ? ' This body needs significant attention.' : weakest.avg < 60 ? ' This body is building but not yet stable.' : ' Good progress — continue deepening.'}`}</>
            }
          </div>
        </div>

        {/* Share button */}
        <button onClick={copyReport}
          style={{ width: '100%', padding: '14px', borderRadius: 10, border: 'none', background: copied ? '#1D9E75' : '#1a1a18', color: '#fff', fontSize: 14, fontWeight: 600, cursor: 'pointer', marginBottom: 10 }}>
          {copied ? '✓ Report copied to clipboard' : '↗ Copy report for session'}
        </button>
        <div style={{ textAlign: 'center', fontSize: 11, color: '#888', lineHeight: 1.6 }}>
          Copy this report and share with your practitioner or coach before your session. Generated by Quintave — quintave.vercel.app
        </div>
      </div>
    </div>
  )
}
